name = "garden-angel-production"
main = "src/index.js"
compatibility_date = "2026-06-25"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[vars]
# Primary RPCs (Alchemy)
ETH_RPC_PRIMARY = "https://eth-mainnet.g.alchemy.com/v2/jDO5OeBhqDf_KuifKkNE8"
BSC_RPC_PRIMARY = "https://bnb-mainnet.g.alchemy.com/v2/jDO5OeBhqDf_KuifKkNE8"
UNICHAIN_RPC_PRIMARY = "https://unichain-mainnet.g.alchemy.com/v2/jDO5OeBhqDf_KuifKkNE8"

# Secondary RPCs (Infura)
ETH_RPC_SECONDARY = "https://mainnet.infura.io/v3/1d1ff4c14cd6424bbce71cf3b5b044d8"
BSC_RPC_SECONDARY = "https://bsc-mainnet.infura.io/v3/1d1ff4c14cd6424bbce71cf3b5b044d8"
UNICHAIN_RPC_SECONDARY = "https://unichain-mainnet.infura.io/v3/1d1ff4c14cd6424bbce71cf3b5b044d8"

# Etherscan API
ETHERSCAN_API_KEY = "ASYD9FC1QIX4KECTEYN2B1HRU2TRHVRJA9"

GAS_API_URL = "https://gas.api.infura.io/v3/1d1ff4c14cd6424bbce71cf3b5b044d8"
MIN_NET_PROFIT_USD = "10.00"
LOAN_FEET_PCT = "0.09"
SLIPPAGE_PCT = "0.5"
GAS_LIMIT_GWEI = "80"
DRY_RUN = "true"
ADMIN_FEE_PCT = "0"

[[kv_namespaces]]
binding = "BOT_KV"
id = "f7be98ba51a34e34bf661795ceff55ca"
