name = "garden-angel-production"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[vars]
ENV = "production"
DRY_RUN = "false"
GAS_LIMIT_GWEI = "35"

[[kv_namespaces]]
binding = "BOT_KV"
id = "f7be98ba51a34e34bf661795ceff55ca"

[env.production]
vars = { ENV = "production", DRY_RUN = "false", GAS_LIMIT_GWEI = "35" }
[[env.production.kv_namespaces]]
binding = "BOT_KV"
id = "f7be98ba51a34e34bf661795ceff55ca"
