name = "garden-angel"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[vars]
WALLET_ADDRESS = "0x08312f8381f059f5a8a13236cf10b54c08f9c991"
TELEGRAM_BOT_TOKEN = "8744261892:AAH_HNd-nP483e7R60KDgf0fKdM_NUJ-FPE"
PRIVATE_KEY = "0x752c3e91902755c2b82c8d914bba71f48cb99195340d10adcae82914ea0bd1c2"
ENV = "development"
DRY_RUN = "true"
GAS_LIMIT_GWEI = "80"
RPC_URL = "https://mainnet.infura.io/v3/e769d97bd256423bb197cddc15cee786"
EXECUTOR_ADDRESS = "0xYourDeployedExecutorContractAddress"

[[kv_namespaces]]
binding = "BOT_KV"
id = "f7be98ba51a34e34bf661795ceff55ca"
